### ISSUE TITLE
A few mistakes

### ISSUE THREAD

**Issue by daffyyyy** [TeaSpeak/TeaSpeak#223] opened 2018-07-10 19:44 UTC
## System Information
***Operating System***: Debian 9
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 
buildVersion.txt
1.1.38-beta
Packed version: 5

## Issue
***Reason for reporting this issue***:
First problem:
I want users to be able to move users on own channels

Second problem:
Annoying problem when suddenly throws users out for a reason

Third problem:
The server can not be added to the list so it can not be promoted in this way

***Detailed Description***:

First problem:
Channel ranks can not move users always pops up
<21:28:11> insufficient client permissions (failed on i_client_move_power)
No difference whether set to 0 or 100

Second problem:
Sometimes pops:
<20:23:14> Disconnected from server (parameter not found)

Third problem:
The server can not be added to the gametracker, all permits set and ip unblocked

**Comment by xRedFox** [comment] 2018-07-10 19:57
Do you use MySQL db?

**Comment by daffyyyy** [comment] 2018-07-10 20:03
SQLite, fresh teaspeak installation same problems

**Comment by xRedFox** [comment] 2018-07-11 12:06
**I can confirm the second problem:** From yesterday the server throws me out with "ping timeout" every 10 seconds for a dozen times then pause for a period and then start again.

**Comment by WolverinDEV** [comment] 2018-07-12 11:47
Hey,
Well the ping timeout isn't the same as the kick thing.
Well which Action do you perform when this happens?
Because I have no idea where who's could happen. 

And can you describe the channel move thing a little it closer?

**Comment by daffyyyy** [comment] 2018-07-12 17:42
Next issue:
High ram usage with 1 server (1 virtualserver) and ~15 clients online
https://i.imgur.com/LeJDkn8.png

**Comment by WolverinDEV** [comment] 2018-07-12 17:46
Hmm quite funny (the ram usage).
Well does it also happen when you're not having any music bots?

```
Users mass (disconnecting) when friends try to edit server permissions or properties. I have no idea what, no one edits anything for safety.
```
I need the exact thing when everybody disconnects because I have to reproduce it to find out which property it is.

**Comment by WolverinDEV** [comment] 2018-07-12 17:47
"
The server can not be added to the gametracker, all permits set and ip unblocked"
May wrong query MOTD?

**Comment by WolverinDEV** [comment] 2018-07-12 17:49
Moved out the moving issue to #225

**Comment by daffyyyy** [comment] 2018-07-12 17:51
>  May wrong query MOTD?
Ye, all is set correctly. 
Will try with the usual motd, although I added the "TS3" at the beginning and it did not work, I find somewhere the TeamSpeak3 server's proper motd?

**Comment by daffyyyy** [comment] 2018-07-12 17:55
The high usage of RAM has started today with normal server operation. Nothing was changed, and suddenly such jumps

**Comment by WolverinDEV** [comment] 2018-07-12 18:05
Hmm okey the ram usage is unusual.
I'll look at this when I'm at home.
Therefore I don't have the possibilities to debug that.

**Comment by daffyyyy** [comment] 2018-07-12 18:13
Okay :) Thanks, usage of the ram is slowly growing, but i can restart server. BTW high ram usage may be caused by file transfer. I'm reading logs and I do not see anything except for a large number of file transfers as well as [Permission]

**Comment by WolverinDEV** [comment] 2018-07-13 17:11
Wel I'll close this issue for the first because there isn't anything more than just the high ram usage, which I cant track now.

**Closed by WolverinDEV** 2018-07-13 17:11 UTC
