### ISSUE TITLE
Snapshot incorrectly transfers server settings

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#420] opened 2018-09-10 06:17 UTC
**Describe the bug**
After the restore, a different value is always set: `virtualserver_upload_quota=500` and `virtualserver_download_quota=-1`

**Screenshots**
Steps to reproduce the behaviour:
1. Before creating a snapshot: https://prnt.sc/ksk61w
2. After the snapshot recovery: https://prnt.sc/kska5f

**Environment information:**
 Operating system: Debian 9.3
 TeaSpeak version: TeaSpeak-1.2.16-beta-1
 I am using `experimental_31`: yes

**Additional context**
The values of `virtualserver_upload_quota` and` virtualserver_download_quota` were assigned by default, but should have been by snapshot.

**Comment by WolverinDEV** [comment] 2018-09-10 08:27
I guess the value within the snapshot is the large number.
Because I'm using signed numbers internally I reset that to - 1 again.

But I have no clue where the 500 comes from

**Comment by REDMONDS** [comment] 2018-09-10 08:37
try to reproduce it))

**Comment by Chazotu** [comment] 2018-09-10 15:58
confirmed got it reproduced also getting the 500

**Comment by WolverinDEV** [comment] 2018-09-10 16:30
Fixed within the next build/version

**Closed by WolverinDEV** 2018-09-10 16:30 UTC
Labels: bug, verified
