### ISSUE TITLE
Unordered packet queue index increased from XXXX to XXXX for type Ack

### ISSUE THREAD

**Issue by zafai** [TeaSpeak/TeaSpeak#611] opened 2019-07-05 06:56 UTC
**Describe the bug**
2 externs audio bot are unable to join and produce massive log spam please see logfile section.

I found this thread https://forum.teaspeak.de/index.php?threads/leute-k%C3%B6nnen-nicht-reden-h%C3%B6ren.1983/

**Logs**
```
2019-07-05 08:49:48] [WARNING]     3 | [XX.XX.XXX.XXX:38086/Radio #1 | 1] Unordered packet queue index increased from 2268 to 2269 for type Ack
[2019-07-05 08:49:48] [DEBUG]     3 | [XX.XX.XXX.XXX:38086/Radio #1 | 1] Got unordered packet of type Ack which is out of the buffer range of 32. Packet ID: 2270, Current index: 2269. Dropping packet
[2019-07-05 08:49:48] [WARNING]     3 | [XX.XX.XXX.XXX:38086/Radio #1 | 1] Unordered packet queue index increased from 2269 to 2270 for type Ack
[2019-07-05 08:49:48] [DEBUG]     3 | [XX.XX.XXX.XXX:38086/Radio #1 | 1] Got unordered packet of type Ack which is out of the buffer range of 32. Packet ID: 2271, Current index: 2270. Dropping packet
[2019-07-05 08:49:48] [WARNING]     3 | [XX.XX.XXX.XXX:38086/Radio #1 | 1] Unordered packet queue index increased from 2270 to 2271 for type Ack
[2019-07-05 08:49:48] [DEBUG]     3 | [XX.XX.XXX.XXX:38086/Radio #1 | 1] Got unordered packet of type Ack which is out of the buffer range of 32. Packet ID: 2272, Current index: 2271. Dropping packet
[2019-07-05 08:49:48] [WARNING]     3 | [XX.XX.XXX.XXX:38086/Radio #1 | 1] Unordered packet queue index increased from 2271 to 2272 for type Ack
[2019-07-05 08:49:48] [DEBUG]     3 | [XX.XX.XXX.XXX:38086/Radio #1 | 1] Got unordered packet of type Ack which is out of the buffer range of 32. Packet ID: 2273, Current index: 2272. Dropping packet
[2019-07-05 08:49:48] [WARNING]     3 | [XX.XX.XXX.XXX:38086/Radio #1 | 1] Unordered packet queue index increased from 2272 to 2273 for type Ack
[2019-07-05 08:49:48] [DEBUG]     3 | [XX.XX.XXX.XXX:38086/Radio #1 | 1] Got unordered packet of type Ack which is out of the buffer range of 32. Packet ID: 2274, Current index: 2273. Dropping packet

```
**Environment information:**
 Operating system: debian 9.9
 TeaSpeak version: TeaSpeak-1.3.21-beta-7
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment] 2019-07-06 20:28
Well thats not really an issue.
It just looks like the client is lagging a bit :)

**Comment by DDDD5** [comment] 2019-07-08 14:34
A friend who has 1Gbps of band (and 5ms of stable ping) has the same problem

**Comment by zafai** [comment] 2019-07-08 14:39
This only happens with the TeaSpeak-1.3.21-beta-7 currently I'm using the 1.3.19 (Stable) without this problem

**Comment by WolverinDEV** [comment] 2019-07-09 11:24
Hey,
Use 1.3.21-beta10 please and see the results :)

**Comment by zafai** [comment] 2019-07-10 06:34
Hey,
just tried version 1.3.21-beta10 and got the same problem.

**Comment by WolverinDEV** [comment] 2019-07-14 22:43
Whats within the log?

**Comment by zafai** [comment] 2019-07-18 06:54
I just tried version 1.3.22-beta-2 with the same problem

got this message in the logfile and after some time the server crashed crash_dump is attached.

[crash_dump_0c337757-8efa-44ea-5dc3b19d-68d9d6d7.dmp.zip](https://github.com/TeaSpeak/TeaSpeak/files/3405143/crash_dump_0c337757-8efa-44ea-5dc3b19d-68d9d6d7.dmp.zip)

`[2019-07-18 08:45:10] [DEBUG]     3 | [94.23.XXX.XXX:49013/undefined | 0][Ack] Ignoring ack for 1
[2019-07-18 08:45:10] [DEBUG]     3 | [94.23.XXX.XXX:49013/undefined | 0] Got client ek!
[2019-07-18 08:45:10] [DEBUG]     3 | [94.23.XXX.XXX:49013/undefined | 0] Failed to handle acknowledge: Missing packet id (1)
[2019-07-18 08:45:10] [DEBUG]     3 | [Property] Changing client property 'client_totalconnections' for 1094 (New value: 109, SQL: UPDATE `clients` SET `connections` = :value WHERE `serverId` = :serverId AND `cldbid` = :cldbid)
[2019-07-18 08:45:10] [DEBUG]     3 | [94.23.XXX.XXX:54294/Client #2 | 1] Got unordered packet of type Ack which is out of the buffer range of 32. Packet ID: 48, Full index: 33. Dropping packet
[2019-07-18 08:45:10] [WARNING]     3 | [94.23.XXX.XXX:54294/Client #2 | 1] Unordered packet queue index increased from 33 to 48 for type Ack
[2019-07-18 08:45:10] [DEBUG]     3 | [94.23.XXX.XXX:54294/Client #2 | 1] Got unordered packet of type Ack which is out of the buffer range of 32. Packet ID: 50, Full index: 49. Dropping packet
[2019-07-18 08:45:10] [WARNING]     3 | [94.23.XXX.XXX:54294/Client #2 | 1] Unordered packet queue index increased from 49 to 50 for type Ack
[2019-07-18 08:45:10] [DEBUG]     3 | [94.23.XXX.XXX:54294/Client #2 | 1] Got unordered packet of type Ack which is out of the buffer range of 32. Packet ID: 52, Full index: 51. Dropping packet
`

**Comment by WolverinDEV** [comment] 2019-07-19 10:43
Tryout beta 5 :)
I've changed some stuff there, As well the crash fixed there as well

**Comment by zafai** [comment] 2019-07-30 07:37
I just installed 1.3.22-beta-10 the message still get written like 2500 into the logfile but then it stops and the client is working.

**Comment by WolverinDEV** [comment] 2019-07-31 21:21
Yeahr I've done there some stuff.
The voice issue might be fixed soon as well :)

**Comment by WolverinDEV** [comment] 2019-08-01 09:54
--- Update ---
I'm having a hot idea where the voice shattering issue is caused by.
My local tests already showed an improvement!
Please test out TeaSpeakServer-1.3.22-beta12.

**Comment by WolverinDEV** [comment] 2019-09-18 23:00
I'm considering this as fixed now, because of the good feedback of all other users.

**Closed by WolverinDEV** 2019-09-18 23:00 UTC
Labels: help wanted
