### ISSUE TITLE
Log path

### ISSUE THREAD

**Issue by DrN00bish** [TeaSpeak/TeaSpeak#333] opened 2018-08-20 14:18 UTC
Tried changing the log path to "logs/log_${time}(%Y-%m-%d_%H.%M.%S)_${group}.log" but didn't seem to actually change the filename.

/ReallyLowPriority

**Comment by WolverinDEV** [comment] 2018-08-20 14:20
Where is the problem there?

**Comment by WolverinDEV** [comment] 2018-08-20 17:43
Well i cant reproduce that.
For example: "path: logs_______/log?_${time}(%Y_%m_%d_%H_%M_%S)_:_${group}.log" worked for me

**Comment by DrN00bish** [comment] 2018-08-20 17:46
That's strange. I'll have to retry it on another server. Brb with results of that

**Comment by WolverinDEV** [comment] 2018-08-26 10:50
You were right.
Im sorry i just forgot to use the pattern :D
```
auto pattern = !value.empty() ? value[0] : "%Y-%m-%d_%H:%M:%S";

tm* tm_info;
auto secs = duration_cast<seconds>(logConfig->timestamp.time_since_epoch()).count();
tm_info = localtime((time_t*) &secs);

char timeBuffer[128];
strftime(timeBuffer, 128, "%Y-%m-%d_%H:%M:%S", tm_info);

return string(timeBuffer);
```

Fixed within the next version :)

**Closed** 2018-08-26 10:52 UTC
Labels: help wanted
