### ISSUE TITLE
Musicbot improvements

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#168] opened 2018-06-06 23:22 UTC
- [ ] Auto select musicbot when `targetmode=1` and `target=<musicbotclientid>`
- [x] Auto select created bot upon creation
- [ ] Rename `i_client_music_info` to `i_client_music_info_power` and `i_client_music_needed_info` to `i_client_music_needed_info_power` to stay consistent
- [ ] Listen for chat commands in serverchat
- [ ] New permission to allow/deny chat commands `b_client_use_chat_commands`
- [ ] New config value for command prefix
- [ ] Merge bot info into one message (it just doesnt feel right if 20 messages are needed to show that)
- [ ] Some way to make teaspeak musicbots less obvious (maybe allow premium license owners to change the default generated uid to their liking without modifying the db)
- ~~If stream URL is already being downloaded because it's running on another bot on the instance just re-use that stream instead of requesting it again~~ (Its impossible)
- ~~If youtube audio is already cached and requested again use the cached one~~ (Data is already cache, but stream caching is not possible)
- [ ] Implement some kind of TTS library to allow stuff like `.mbot voice Anna`, `.mbot speed 0.5`, `.mbot pitch 1.5`, `.mbot say Welcome to our Teamspeak server`
- [ ] Implement `b_client_music_autodelete` to autodelete musicbots of the creator on disconnect.

**Comment by Bluscream** [comment] 2018-06-06 23:41
# Whisper System

- `.mbot mode "whisper"/"channel"`
- `.mbot (un)sub <"channel">` `b_client_music_subscribe_power`,`b_client_needed_music_subscribe_power`

**Comment by Bluscream** [comment] 2018-06-06 23:54
## Plugin Friendly

Use `client_meta_data` variable to store musicbot infos:
```xml
<bots>
<bot type="music" id=496 "I am a musicbot!">
<playing>vol=0.050000 state=2 title="I Love Radio" src="http://stream01.iloveradio.de/iloveradio1.mp3" artist="" timeline="366/0" buffered
<queue>
<
</queue>
</bot>
</bots>
```

## Nvm this, have to rethink it again

**Comment by WolverinDEV** [comment] 2018-06-15 19:23
What do you mean with your last post "Plugin Friendly"?

**Comment by Bluscream** [comment] 2018-06-16 03:03
> What do you mean with your last post "Plugin Friendly"?

"Legit" plugins can't access low level commands, they have to use the plugin API. So they have to either use plugin commands or read/set the client_meta_data variable :o

**Comment by xRedFox** [comment] 2018-06-25 18:32
- I propose to modify the `.mbot volume <0-1>` in `.mbot volume <0-100>`. Usually the scale is from 1 to 100 on every app/system.
- `.mbot volume` (without args) kicks you from the server with `You were kicked from the server by the Server (Invalid argument)` message. **[BUG]**
- `.mbot volume -0` is allowed? rly? ahahaha
- A command that requires parameters, if not supplied, returns `Invalid argument count`. I think it's more practical to return a message with the usage, for example
```Invalid number of arguments! Usage: ".mbot volume <0-1>"```
(It's just an idea and maybe is wrong xD)

**Comment by xRedFox** [comment] 2018-06-28 05:30
Ah yeah @WolverinDEV one more thing, how does the `.mbot player <provider> <data>` work?

**Comment by xRedFox** [comment] 2018-06-28 06:01
A better playlist (maybe more than one for non premium users pleeezzz):
- create/delete/manage a playlist
`.mbot playlist [ list ] [ <server> | <channel> ]`
`.mbot playlist [ create ] <playlist name>`
`.mbot playlist [ remove | rename | loop | info ] [ <playlist name> | <playlist id> ]`
- add/delete from playlist
`.mbot playlist [ addmusic | removemusic ] <playlist name> <url>`
- Global playlist (great idea for playlist template)

Another thing no longer related to the playlist, can we make that `.mbot select [...]` can also select musicbot by name? `.mbot select [ <musicbot-id> | <musicbot-name> ] `

**Comment by WolverinDEV** [comment] 2018-06-28 07:35
Uhh I really like the last idea with the Playlist.
I already could say that I will implement something like that. 
I can't be sure if I really implement that stuff as a text command or just over the web interface (but it will be available via query commands as well).

The thing with mbot volume was just a mistake and will be fixed. 
As well the range from one to 100.

**Comment by WolverinDEV** [comment] 2018-06-29 09:39
@xRedFox 
All you're sound improvements or bugs are fixed :)
Now its `.mbot volume` -> Sends you the bot volume from 1-100%
And `.mbot volume 55.5` -> Sets the music bot volume to 55.5%

**Comment by xRedFox** [comment] 2018-06-30 08:30
The scale of `.mbot volume` is 0-1.
My bot still prints 6 decimal places. Is this a problem related to my database?

![dd](https://user-images.githubusercontent.com/19707386/42123334-82918aaa-7c50-11e8-8c49-bbb27d00ff74.PNG)

**Comment by xRedFox** [comment] 2018-06-30 09:01
Another thing to add as an improvement would be the time of activity of the musicbot.
Currently the "online since" does not take into account that the server has been restarted. I think the best solution would be this:

```
[...]

//
// int musicbotCreationTime is the result in seconds of time since creation
// (example: 10 days = 864000 seconds)
// int serverUptime is the server uptime in seconds
//

int getMusicbotUptime ( int musicbotCreationTime, int serverUptime ) { 
   if ( musicbotCreationTime > serverUptime )  {
      return serverUptime;
   }
   return musicbotCreationTime;
}

[...]
```

If the server is restarted, the `musicbotCreationTime` will always be greater than `serverUptime` and in this case the uptime of the musicbot must be equal to the server's uptime. Otherwise, the function returns the calculation that is done in the actual version of teaspeak server that is all the time elapsed since the creation of the bot.

**Comment by WolverinDEV** [comment] 2018-06-30 10:29
`.mbot volume` is not fixed. Was just a "display" error because im calculating with the range between zero and one :)

And well i cant really understand why it should be the server uptime for music bots.
My idea behind was that you could see how long the music bot ever lived, as a little gimmick

**Comment by xRedFox** [comment] 2018-06-30 12:36
I have another idea (lol)
can we make the musicbot write on song change the currently reproduced song in the channel? (with on/off switch... Not everybody want to hear *PLINT* every song change xD)

Example:
`<66:66:66> "NiceBot": Now playing: How to break wolverindev balls feat. redfox and co.`

And maybe even change the description of the bot with the name of the song played so when a person enters the channel can see the name of the song quickly.

**Comment by Chazotu** [comment] 2018-08-05 15:47
- Listen for chat commands in privatchats
- Make it posible to define the default Shown Bot Version in the config.yml 
- Add an .mbot.description Command
- Make the Bot IDs look more legit

**Comment by Chazotu** [comment] 2018-08-08 13:56
https://github.com/TeaSpeak/TeaMusic/issues

**Comment by Chazotu** [comment] 2018-08-09 23:34
TeaMusic Bot Stuff moved to https://github.com/TeaSpeak/TeaMusic/issues

**Closed by Chazotu** 2018-08-09 23:34 UTC
Labels: enhancement, p:low
