### ISSUE TITLE
syntax error at teastart_minimal.sh

### ISSUE THREAD

**Issue by essemX** [TeaSpeak/TeaSpeak#65] opened 2018-03-02 17:43 UTC
## System Information
***Operating System***: Debian
***Operating System Type*** (x86|x64): amd64
***TeaSpeak Version***: 1.1.0-beta-33

## Issue
***Detailed Description***:
```
ts@host:~/teaspeak$ sh teastart_minimal.sh
teastart_minimal.sh: 10: teastart_minimal.sh: Syntax error: "do" unexpected (expecting "fi")
ts@host:~/teaspeak$ dpkg-query: package 'libav-tools' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
```

**Comment by WolverinDEV** [comment] 2018-03-02 18:08
Hmm thats funny :D
For me everything works

**Comment by essemX** [comment] 2018-03-02 20:05
Debian 8.10

**Comment by WolverinDEV** [comment] 2018-03-03 06:43
Hmm thats really funny, caused by the fact that debian should support selects
(https://www.gnu.org/software/bash/manual/bashref.html#index-select)

**Comment by essemX** [comment] 2018-03-04 00:37
also it seems like libav-tools and a part of ffmpeg are incompatible:
```
ts@v22016083754136591:~/teaspeak$ sh teastart_minimal.sh
teastart_minimal.sh: 10: teastart_minimal.sh: Syntax error: "do" unexpected (expecting "fi")
ts@v22016083754136591:~/teaspeak$ Package: libav-tools
Status: deinstall ok config-files
Priority: optional
Section: video
Installed-Size: 2846
Maintainer: Debian Multimedia Maintainers <pkg-multimedia-maintainers@lists.alioth.debian.org>
Architecture: amd64
Source: libav
Version: 6:11.12-1~deb8u1
Config-Version: 6:11.12-1~deb8u1
Replaces: libavcodec-extra-53 (<< 4:0.6~)
Depends: libavcodec56 (>= 6:11~beta1) | libavcodec-extra-56 (>= 6:11.12), libavdevice55 (>= 6:11~beta1), libavfilter5 (>= 6:11~beta1), libavformat56 (>= 6:11~beta1), libavresample2 (>= 6:11~beta1), libavutil54 (>= 6:11~beta1), libc6 (>= 2.14), libsdl1.2debian (>= 1.2.11), libswscale3 (>= 6:11~beta1), libvdpau1 (>= 0.2), libx11-6
Pre-Depends: dpkg (>= 1.15.7.2~)
Suggests: frei0r-plugins (>= 1.3)
Conflicts: ffprobe
Description: Multimedia player, encoder and transcoder
 Libav is a complete, cross-platform solution to decode, encode, record,
 convert and stream audio and video.
 .
 This package contains the avplay multimedia player, the avconv audio
 and video encoder, and the avprobe stream analyzer.  They support most
 existing file formats (AVI, MPEG, OGG, Matroska, ASF...) and encoding
 formats (MPEG, DivX, MPEG4, AC3, DV...). Additionally, it contains the
 qt-faststart utility which rearranges Quicktime files to facilitate
 network streaming.
 .
 This package replaces the 'ffmpeg' command-line tool that was provided
 in earlier distroreleases.
Homepage: http://libav.org/
^C
```

**Comment by WolverinDEV** [comment] 2018-03-10 08:24
Hey,
it sould not be incompatible, you should be abe to use ffmpeg with libav (caused by the reason that ffmpeg depends on libav :))

Update:
I fixed the select case in the script (using another system now)

**Comment by essemX** [comment] 2018-03-10 18:10
```
# unzip and removing TeaSpeak-1.1.2-beta.tar.gz
# now updated to 1.1.2-beta
ts@v22016083754136591:~/teaspeak$ sh teastart_minimal.sh
teastart_minimal.sh: 10: teastart_minimal.sh: Syntax error: "(" unexpected (expecting "then")
ts@v22016083754136591:~/teaspeak$ Package: libav-tools
Status: deinstall ok config-files
Priority: optional
Section: video
Installed-Size: 2846
Maintainer: Debian Multimedia Maintainers <pkg-multimedia-maintainers@lists.alioth.debian.org>
Architecture: amd64
Source: libav
Version: 6:11.12-1~deb8u1
Config-Version: 6:11.12-1~deb8u1
Replaces: libavcodec-extra-53 (<< 4:0.6~)
Depends: libavcodec56 (>= 6:11~beta1) | libavcodec-extra-56 (>= 6:11.12), libavdevice55 (>= 6:11~beta1), libavfilter5 (>= 6:11~beta1), libavformat56 (>= 6:11~beta1), libavresample2 (>= 6:11~beta1), libavutil54 (>= 6:11~beta1), libc6 (>= 2.14), libsdl1.2debian (>= 1.2.11), libswscale3 (>= 6:11~beta1), libvdpau1 (>= 0.2), libx11-6
Pre-Depends: dpkg (>= 1.15.7.2~)
Suggests: frei0r-plugins (>= 1.3)
Conflicts: ffprobe
Description: Multimedia player, encoder and transcoder
 Libav is a complete, cross-platform solution to decode, encode, record,
 convert and stream audio and video.
 .
 This package contains the avplay multimedia player, the avconv audio
 and video encoder, and the avprobe stream analyzer.  They support most
 existing file formats (AVI, MPEG, OGG, Matroska, ASF...) and encoding
 formats (MPEG, DivX, MPEG4, AC3, DV...). Additionally, it contains the
 qt-faststart utility which rearranges Quicktime files to facilitate
 network streaming.
 .
 This package replaces the 'ffmpeg' command-line tool that was provided
 in earlier distroreleases.
Homepage: http://libav.org/
^C
```
the only working way currently for me to start a server is "sh teastart.sh start".
"teastart_minimal.sh" and "./TeaSpeakServer" both don't work on its own

**Comment by WolverinDEV** [comment] 2018-03-26 04:45
Should be fixed

**Closed by WolverinDEV** 2018-03-26 04:45 UTC
Labels: bug
