### ISSUE TITLE
First connection failed

### ISSUE THREAD

**Issue by SossenSystems** [TeaSpeak/TeaSpeak#262] opened 2018-08-08 12:36 UTC
First attempt to connect always fails.
The second one always works.
```
￼<14:28:20> Versuche zum Server auf 54.36.135.226 zu verbinden
￼<14:28:26> Verbindung zum Server fehlgeschlagen
￼<14:28:32> Versuche zum Server auf 54.36.135.226 zu verbinden
￼<14:28:33> Welcome Message [...] // successfully
```
The server is hosted at StartyourServer (OVH-Game).
I believe that this is rather a problem with DDoS protection... Was to see at the first time on T***Speak 3.1(.0) too.

**Comment by WolverinDEV** [comment] 2018-08-08 12:37
Duplicate of #232

**Closed by WolverinDEV** 2018-08-08 12:37 UTC
