### ISSUE TITLE
TS client crashes while connecting to the server

### ISSUE THREAD

**Issue by xRedFox** [TeaSpeak/TeaSpeak#128] opened 2018-05-18 07:39 UTC
## System Information
***Operating System***: ArchLinux
***Operating System Type*** (x86|x64): x86_64
***TeaSpeak Version***: 1.1.25 beta 7 (ts3dump_1526627964322) and before

## Issue
***Reason for reporting this issue***:
Bug

***Detailed Description***:
TeamSpeak3 client crashes about 1 time out of 8 when connecting to a TeaSpeak server

**Client dumps here:** [crashdumps.zip](https://github.com/TeaSpeak/TeaSpeak/files/2015919/crashdumps.zip) _(latest is ts3dump_1526627964322)_
**Server logs here:** [log_2018-05-18_09_07_40_general.log](https://github.com/TeaSpeak/TeaSpeak/files/2015917/log_2018-05-18_09_07_40_general.log) _(only the latest)_

**Comment by WolverinDEV** [comment] 2018-05-19 15:56
Should be fixed. 

BTW: I cant do anythink with the crashdump of the client :/ I dont have any TeamSpeak sources :)

**Comment by xRedFox** [comment] 2018-05-20 17:51
Unfortunately the client continues to crash on 1.1.26 beta 5

**This is what happens on the server:**
```
[19:44:15] [DEBUG]   1 | [151.18.97.185:29080/RedFox]Client ping timeout (15439)
[19:44:15] [DEBUG]   1 | [151.18.97.185:29080/RedFox]Attemp to close connection. (Flush data: 1)
[19:44:15] [DEBUG]   1 | [151.18.97.185:29080/RedFox]Awaiting write prepare, write and acknowledge queue flushed
[19:44:15] [DEBUG]   1 | [151.18.97.185:29080/RedFox]Write prepare queue progressed
[19:44:15] [DEBUG]   1 | [151.18.97.185:29080/RedFox]Write and acknowledge queue flushed
[19:44:15] [INFO]   1 | Client RedFox (151.18.97.185:29080) disconnects. (UID: dJKdU8NNyGdnjWzEPCzE+Qv1VEI= Database ID: 3)
```
Full server log here: [log_2018-05-20_15_49_22_general.log](https://github.com/TeaSpeak/TeaSpeak/files/2020526/log_2018-05-20_15_49_22_general.log)

**Comment by WolverinDEV** [comment] 2018-05-20 18:05
Do you have the crash message of the client?
(Start the client with the -console parameter)

**Comment by xRedFox** [comment] 2018-05-20 19:28
At the moment I couldn't recreate the error but I managed to crash the entire server xD
Logs: [log_2018-05-20_15_49_22_general.log](https://github.com/TeaSpeak/TeaSpeak/files/2020620/log_2018-05-20_15_49_22_general.log)
Dump: [crash_dump_1f3884b9-e3eb-4a9a-d914f98a-f72b8074.zip](https://github.com/TeaSpeak/TeaSpeak/files/2020622/crash_dump_1f3884b9-e3eb-4a9a-d914f98a-f72b8074.zip)
It happened when I stopped the id 1 server from yatqa
I know it has nothing to do with the title of this thread but I'm lazy. LOL.

**Comment by WolverinDEV** [comment] 2018-05-23 11:48
Ahh yeah thats a really rare error (i just could produce it in 1 out of 100)
The problem is that i need to know which packet causes that, and i still now updated my TS3 protocol hook to linux :D

**Comment by WolverinDEV** [comment] 2018-06-04 13:27
Should be fixed (found a (the) logic error)
Will be released within the next version

**Comment by WolverinDEV** [comment] 2018-06-06 18:48
Should be fixed

**Closed by WolverinDEV** 2018-06-06 18:48 UTC
Labels: bug, verified
