### ISSUE TITLE
Transfer config locked?

### ISSUE THREAD

**Issue by fedecingo** [TeaSpeak/TeaSpeak#313] opened 2018-08-18 07:44 UTC
I have the transfer config locked in this value? If i edit this it comes anyway (i am running TeaSpeak 1.2.9-beta)

![locked](https://user-images.githubusercontent.com/32389206/44297064-f4dcba80-a2ca-11e8-8d79-dfea07f4ed2f.png)

**Comment by MikkelDK** [comment] 2018-08-18 08:02
Duplicted. #264

**Comment by WolverinDEV** [comment] 2018-08-18 08:35
Duplicate of #264

**Closed** 2018-08-18 08:35 UTC
