### ISSUE TITLE
Arabic Letters In Channel Name

### ISSUE THREAD

**Issue by iJosephY** [TeaSpeak/TeaSpeak#345] opened 2018-08-21 17:18 UTC
**Describe the bug**
When i try to name a chennel in arabic i got an invalid channel name error
Creating spacers in arabic works fine, the issue is only in rooms

**Environment information:**
 Operating system: (`Ubuntu 16.04`)
 TeaSpeak version: [TeaSpeak-1.2.11b]

**Comment by WolverinDEV** [comment] 2018-08-21 17:26
Yeah,
I know Cyrillic  characters doesn't work as well :)

**Comment by iJosephY** [comment] 2018-08-21 17:28
Also when i create a temporary room .. then i change 
Max Users to Limited and Family Max Users 
the server crash

**Comment by WolverinDEV** [comment] 2018-08-21 17:47
Duplicate of #339

**Closed by WolverinDEV** 2018-08-21 17:47 UTC
Labels: bug, p:medium
