### ISSUE TITLE
Ghosts

### ISSUE THREAD

**Issue by i-Clyde** [TeaSpeak/TeaSpeak#370] opened 2018-08-27 13:40 UTC
**Describe the bug**
Sometimes after (X minutes/hours) of conversation one or more user getting ghost powers which allows him to see and hear others but nobody can see and hear him. It happens also in second way ghosts sometimes can't see half of users in channel but half cant see him. It looks like timeout it can happen during the conversation. No information about disconnect or channel join/leave just like a ghost. It happens even when everybody in channel got latest version of teamspeak (im using latest of teaspeak). 

**To Reproduce**
Not really know how to reproduce that, one day is without ghosts and second is. 

**Expected behaviour**
You've got a one user who can see chosen users. And probably nobody can see him.  

**Environment information:**
Testing on:
  Operating system: Windows 10 (both)
  Operating system: Elementary OS
  Operating system: Linux Mint
  Operating system: OS X High Sierra
 TeaSpeak version: 1.2.13b - on ubuntu server

**Additional context**
It's really weird when you are in channel with person who's talking to somebody but you can't see him. 

**How to FIX**
Ghost need to reconnect to the server, after it (new socket connection) it will calm down for a while.

**Comment by h1rule** [comment] 2018-08-29 06:44
Still happening here to, using the latest Version.

**Comment by WolverinDEV** [comment] 2018-09-01 19:58
Duplicate of #326 
Needs testing is may fixed :)

**Closed by WolverinDEV** 2018-09-01 19:58 UTC
Labels: bug, verified
