### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#232] opened 2018-07-17 02:27 UTC
## System Information
***Operating System***:
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.40 beta 4
## Issue
***Reason for reporting this issue***:
Sometimes can't connect on first time , need retry between 1 time and 10 times  to connect teaspeak server

***Detailed Description***:
exp31 ON.

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment] 2018-07-17 07:10
Well I know that issue.
I will improve that within the next weeks :)

**Comment by daffyyyy** [comment] 2018-07-17 10:59
Same problem without exp31, users needs connect 2 Times to join

**Comment by WolverinDEV** [comment] 2018-07-17 14:25
Ahh yeah you have a firewall infront?

**Comment by daffyyyy** [comment] 2018-07-17 14:30
Yes, im hosted on ovh game, but with all needed ports unblocked

**Comment by MikkelDK** [comment] 2018-07-17 14:32
If you are using 3.2.0 (BETA) client, it wont works (i have tested!)
+ I have tested with EXP31 on (using 3.1.0 client - where connect wont work) :-)

**Comment by Sporesirius** [comment] 2018-07-17 15:09
I also noticed that sometimes it says "Trying to connect to server" twice.

**Comment by xRedFox** [comment] 2018-07-17 15:20
I can confirm too! Sometimes you need to connect twice.

**Comment by WolverinDEV** [comment] 2018-07-17 16:06
Well ovh has a Baltic firewall which is (I thing im not 100% sure) non deactivateible.
The best thing is to test it on localhost. But yes I know the problem and the reason and will "fix" that soon as I see that you really want that.

**Comment by daffyyyy** [comment] 2018-07-17 16:34
Repairing this would involve some major changes or inconveniences for server owner?

**Comment by WolverinDEV** [comment] 2018-07-17 17:38
no it wouldnt

**Comment by daffyyyy** [comment] 2018-07-17 17:43
If it is not a problem, it would be nice if it was fixed, it annoys a bit of people and not what to hide, that a lot of servers are in ovh

**Comment by MikkelDK** [comment] 2018-07-19 13:20
It shouldnt be a problem with OVH Server. i'm too on OVH Server (just without Anti DDoS GAME) ;)

**Comment by WolverinDEV** [comment] 2018-07-22 14:18
Should be fixed/improved as well :)

**Comment by daffyyyy** [comment] 2018-07-24 00:18
Any changes?
1.1.41-beta-2 and problem not resolved

**Comment by WolverinDEV** [comment] 2018-07-24 11:42
@daffyyyy 
Are you sure?
If yes i need the log where the first connect attempt failed, but the second worked.
(Its important to have the full log view there!)

**Comment by daffyyyy** [comment] 2018-07-24 11:56
First time

```
[2018-07-24 13:54:09] [DEBUG]     1 | [xxx.226:8713/undefined] Got handshake timeout. 37.248.156.226:8713. State: INIT_LOW Time: 5
[2018-07-24 13:54:09] [DEBUG]     1 | xxx.226:8713/undefined] Closing voice client connection. (Flush: true)
[2018-07-24 13:54:09] [DEBUG]     1 | [xxx.226:8713/undefined] Awaiting write prepare, write and acknowledge queue flushed
[2018-07-24 13:54:09] [DEBUG]     1 | [xxx.226:8713/undefined] Write prepare queue progressed
[2018-07-24 13:54:09] [DEBUG]     1 | [xxx.226:8713/undefined] Write and acknowledge queue are flushed
[2018-07-24 13:54:09] [INFO]      1 | Voice client 0/ (undefined) from xxx.226:8713 left.
```

Second time he can join

**Comment by WolverinDEV** [comment] 2018-07-24 11:59
**(Its important to have the full log view there!)**

**Comment by daffyyyy** [comment] 2018-07-24 12:00
its trace mode

> [2018-07-24 13:54:00] [DEBUG]     1 | [IP.226:8713/undefined] Creating VoiceClient instance at 0x699eba0
> [2018-07-24 13:54:00] [DEBUG]     1 | Allocated new voice client connection at 0x69ac700
> [2018-07-24 13:54:00] [DEBUG]     1 | Remote address (v4) IP destination address IP
> [2018-07-24 13:54:00] [DEBUG]     1 | Having new voice client. Remote address: IP.226:8713
> [2018-07-24 13:54:00] [TRACE]     1 | [IP.226:8713/undefined] Got low level init packet. Remote step: 0 Server step: 0
> [2018-07-24 13:54:00] [TRACE]     1 | [IP.226:8713/undefined] Got low level init packet. Remote step: 2 Server step: 2
> [2018-07-24 13:54:00] [DEBUG]     1 | Failed handshake for IP.226 (Invalid server cookie response!)
> [2018-07-24 13:54:00] [DEBUG]     1 | [IP.226:8713/undefined] Closing voice client connection. (Flush: false)
> [2018-07-24 13:54:00] [INFO]      1 | Voice client 0/ (undefined) from IP.226:8713 left.
> [2018-07-24 13:54:00] [DEBUG]     1 | Updating server property: virtualserver_last_client_disconnect. New value: 1532433240. Query: UPDATE `properties` SET `value` = :value WHERE `serverId` = :sid AND `type` = :type AND `id` = :id AND `key` = :key
> [2018-07-24 13:54:01] [DEBUG]     1 | [IP.226:8713/undefined] Creating VoiceClient instance at 0x69a75a0
> [2018-07-24 13:54:01] [DEBUG]     1 | Allocated new voice client connection at 0x69a6bf0
> [2018-07-24 13:54:01] [DEBUG]     1 | Remote address (v4) IP destination address IP
> [2018-07-24 13:54:01] [DEBUG]     1 | Having new voice client. Remote address: IP.226:8713
> [2018-07-24 13:54:01] [TRACE]     1 | [IP.226:8713/undefined] Got low level init packet. Remote step: 2 Server step: 0
> [2018-07-24 13:54:01] [DEBUG]     1 | [IP.226:8713/undefined]Invalid handshake packet state 2. Current version: 0
> [2018-07-24 13:54:01] [TRACE]     1 | [IP.226:8713/undefined] Got low level init packet. Remote step: 2 Server step: 0
> [2018-07-24 13:54:01] [DEBUG]     1 | [IP.226:8713/undefined]Invalid handshake packet state 2. Current version: 0
> [2018-07-24 13:54:02] [TRACE]     1 | [IP.226:8713/undefined] Got low level init packet. Remote step: 2 Server step: 0
> [2018-07-24 13:54:02] [DEBUG]     1 | [IP.226:8713/undefined]Invalid handshake packet state 2. Current version: 0
> [2018-07-24 13:54:04] [TRACE]     1 | [IP.226:8713/undefined] Got low level init packet. Remote step: 2 Server step: 0
> [2018-07-24 13:54:04] [DEBUG]     1 | [IP.226:8713/undefined]Invalid handshake packet state 2. Current version: 0
> [2018-07-24 13:54:04] [TRACE]     1 | [83.4.49.5:60049/daffyy][Command][Client -> Server] Processing command: connectioninfoautoupdate connection_server2client_packetloss_speech='0.0000' connection_server2client_packetloss_keepalive='0.0000' connection_server2client_packetloss_control='0.0000' connection_server2client_packetloss_total='0.0000'
> [2018-07-24 13:54:09] [DEBUG]     1 | [IP.226:8713/undefined] Got handshake timeout. IP.226:8713. State: INIT_LOW Time: 5
> [2018-07-24 13:54:09] [DEBUG]     1 | [IP.226:8713/undefined] Closing voice client connection. (Flush: true)
> [2018-07-24 13:54:09] [DEBUG]     1 | [IP.226:8713/undefined] Awaiting write prepare, write and acknowledge queue flushed
> [2018-07-24 13:54:09] [DEBUG]     1 | [IP.226:8713/undefined] Write prepare queue progressed
> [2018-07-24 13:54:09] [DEBUG]     1 | [IP.226:8713/undefined] Write and acknowledge queue are flushed
> [2018-07-24 13:54:09] [INFO]      1 | Voice client 0/ (undefined) from IP.226:8713 left.

**Comment by WolverinDEV** [comment] 2018-07-24 12:10
Ahh okey now I know what the problem is.
Well to explain it short:
When a client connects it has several steps to proceed:
- Coocie exchange (Used for dos protection at the 4th layer (OSI).)
- Handshake riddle (To prevent flood attacks)
- Actual handshake

Okez what happend there above the log now:
- Coocie exchange failed because an implementation from ovh (i guess)
- Server disconnects client
- Server recognice new client (but client still stings he had already passed the exchange)
- Handshake timeout because the different states

**Comment by daffyyyy** [comment] 2018-07-24 12:12
Can be fixed or its problem with ovh and not?

**Comment by WolverinDEV** [comment] 2018-07-24 12:16
No not really.
Just set `enforce_coocie_handshake` to zero

**Comment by daffyyyy** [comment] 2018-07-24 12:17
Then it will be possible to flood the server?

**Comment by daffyyyy** [comment] 2018-07-24 12:41
Okay, then ty for explain me and write solution

**Comment by lemignon** [comment] 2018-08-11 11:07
The problem is not fixed  i have disable cookie and also i don't have the game protection of OVH . 
Some times need 1 more time to connect ...

**Comment by MikkelDK** [comment] 2018-08-11 11:36
@lemignon Do you have try update the teaspeak server?

**Comment by lemignon** [comment] 2018-08-11 12:35
i have latest update,but i have always the problem . less than before but sometimes happen .

**Comment by Bluscream** [comment] 2018-08-14 18:17
Can i set `enforce_cookie: 0` only for specific ips?

**Comment by WolverinDEV** [comment] 2018-08-14 18:41
No you cant

**Comment by lemignon** [comment] 2018-08-15 11:51
it's always happening ... and all the people on my teaspeak complain also need sometimes have to connect 2 times or more ... ?

**Comment by WolverinDEV** [comment] 2018-08-15 12:18
Do you have some verbose log for that?

**Comment by lemignon** [comment] 2018-08-15 15:42
good it seems to be improved with beta 2 but few times left have the failed to connect server 1 time on 10 or so . 

Logs while the failed to connect server are  : 

[2018-08-15 17:38:45] [TRACE]     4 | [Property] Not saving property 'clid', changed for 5 (New value: 0)
[2018-08-15 17:38:45] [DEBUG]     4 | [XXX.XXX.XXX.XXX:54413/undefined] Creating VoiceClient instance at 0x7ff21404e520
[2018-08-15 17:38:45] [DEBUG]     4 | Allocated new voice client connection at 0x7ff214046150
[2018-08-15 17:38:45] [DEBUG]     4 | Remote address (v4) 5.196.177.209 destination address 5.196.177.209
[2018-08-15 17:38:45] [DEBUG]     4 | Having new voice client. Remote address: XXX.XXX.XXX.XXX:54413
[2018-08-15 17:38:45] [TRACE]     4 | [XXX.XXX.XXX.XXX:54413/undefined] Got low level init packet. Remote step: 0 Server step: 0
[2018-08-15 17:38:45] [TRACE]     4 | [XXX.XXX.XXX.XXX:54413/undefined] Got low level init packet. Remote step: 2 Server step: 2
[2018-08-15 17:38:45] [TRACE]     4 | [XXX.XXX.XXX.XXX:54413/undefined] Got low level init packet. Remote step: 4 Server step: 4
[2018-08-15 17:38:45] [DEBUG]     4 | [XXX.XXX.XXX.XXX:54413/undefined] Got client 3.1 protocol with build timestamp 177256836
[2018-08-15 17:38:45] [TRACE]     4 | [XXX.XXX.XXX.XXX:54413/undefined][Command][Server -> Client] Sending command initivexpand2. Command low: false. Full command: initivexpand2 time=1534347525 l=AQA1hUFJiiSs0wFXkYuPUJVcDa6XCrZTcsvkB0Ffzz4CmwIITRXgCqeTYAcAAAAgQW5vbnltb3VzAAA1dSpT8CJyWxSbawb+RKFT1\/rGiS6p5txvcR28nFZDyiAKkc2lCpJ2ZQ== beta=rb+2JYRayUMPTwuXWqJVd2FHK0GkwvvMjZW1BuJ44I84l7S88X4AAM0Llyet7Z8ONMpP2IxL omega=ME0DAgcAAgEgAiEA8AoQBeDDIGbF4x+YLKIZcvBU5H6GPTXLubHB3keYwWMCIQDaQjqhJ28vqLiy8EWmoFu0KcosyiCjyH2kw\/pQ3Z8FbQ== proof=MEUCIQC34MLStG3rRcvy1b48PrNFM8vfLFX3i4bnow9mz57N2AIgJCLsSdRDfu\/ezQRsGAISkOyQkZAotAyoSQmzL686ZWs= root=zQ3irtRjRVCafjz9j2iz3HVVsp3M7HPNGHUPmTgSQIo= ot=1
[2018-08-15 17:38:45] [DEBUG]     4 | [XXX.XXX.XXX.XXX:54413/undefined] Got client ek!
[2018-08-15 17:38:46] [DEBUG]     4 | Cant decrypt packet of type Command. Dropping packet. Error: memory verify failed!
[2018-08-15 17:38:46] [DEBUG]   GEN | Invalid packed pushpack! Current index 2 (generation 0) Packet index 1
[2018-08-15 17:38:46] [DEBUG]     4 | Cant decrypt packet of type Command. Dropping packet. Error: memory verify failed!
[2018-08-15 17:38:46] [DEBUG]   GEN | Invalid packed pushpack! Current index 2 (generation 0) Packet index 1
[2018-08-15 17:38:47] [DEBUG]     4 | Cant decrypt packet of type Command. Dropping packet. Error: memory verify failed!
[2018-08-15 17:38:47] [DEBUG]   GEN | Invalid packed pushpack! Current index 2 (generation 0) Packet index 1
[2018-08-15 17:38:49] [DEBUG]     4 | Cant decrypt packet of type Command. Dropping packet. Error: memory verify failed!
[2018-08-15 17:38:49] [DEBUG]   GEN | Invalid packed pushpack! Current index 2 (generation 0) Packet index 1
[2018-08-15 17:38:51] [DEBUG]     4 | [XXX.XXX.XXX.XXX:54413/undefined] Got handshake timeout. XXX.XXX.XXX.XXX:54413. State: INIT_HIGH Time: 5
[2018-08-15 17:38:51] [DEBUG]     4 | [XXX.XXX.XXX.XXX:54413/undefined] Closing voice client connection. (Flush: true)
[2018-08-15 17:38:51] [DEBUG]     4 | [XXX.XXX.XXX.XXX:54413/undefined] Awaiting write prepare, write and acknowledge queue flushed
[2018-08-15 17:38:51] [DEBUG]     4 | [XXX.XXX.XXX.XXX:54413/undefined] Write prepare queue progressed
[2018-08-15 17:38:51] [DEBUG]     4 | [XXX.XXX.XXX.XXX:54413/undefined] Write and acknowledge queue are flushed
[2018-08-15 17:38:51] [INFO]      4 | Voice client 0/oPCm4ciEb/+xzDRI9f+FgCt3gtI= (undefined) from XXX.XXX.XXX.XXX:54413 left.
[2018-08-15 17:38:51] [DEBUG]     4 | Updating server property: virtualserver_last_client_disconnect. New value: 1534347531. Query: UPDATE `properties` SET `value` = :value WHERE `serverId` = :sid AND `type` = :type AND `id` = :id AND `key` = :key

**Comment by Riddler76** [comment] 2018-08-16 13:39
Cookie : 0
Exp31 :  1

[2018-08-16 15:37:22] [DEBUG]     6 | [xxx.xxx.xxx.xxx:55619/undefined] Creating VoiceClient instance at 0x7f48b0000d90
[2018-08-16 15:37:22] [DEBUG]     6 | Allocated new voice client connection at 0x7f48b0012380
[2018-08-16 15:37:22] [DEBUG]     6 | Remote address (v4) xxx.xxx.xxx.xxx destination address xxx.xxx.xxx.xxx
[2018-08-16 15:37:22] [DEBUG]     6 | Having new voice client. Remote address: xxx.xxx.xxx.xxx:55619
[2018-08-16 15:37:22] [TRACE]     6 | [xxx.xxx.xxx.xxx:55619/undefined] Got low level init packet. Remote step: 0 Server step: 0
[2018-08-16 15:37:22] [TRACE]     6 | [xxx.xxx.xxx.xxx:55619/undefined] Got low level init packet. Remote step: 2 Server step: 2
[2018-08-16 15:37:22] [TRACE]     6 | [xxx.xxx.xxx.xxx:55619/undefined] Got low level init packet. Remote step: 4 Server step: 4
[2018-08-16 15:37:22] [DEBUG]     6 | [xxx.xxx.xxx.xxx:55619/undefined] Got client 3.1 protocol with build timestamp 177256836
[2018-08-16 15:37:22] [TRACE]     6 | [xxx.xxx.xxx.xxx:55619/undefined][Command][Server -> Client] Sending command initivexpand2. Command low: false. Full command: initivexpand2 time=1534426642 l=AQBeiVhB5NMeJ79cduZ9dV\/VhA0sG9sk6KLe\/L644d8b0QIKkqw5DG1IOQEAAAQAVGVhU3BlYWsAAH0M1NI0WpG51hFcB+bAQUVsKnhBH3wAOvUAc6f3v\/GQIAqTArIKk6ty beta=u5FhQqz1smeHXb0BmKlXidJL+woM79W9tdVJvmZxyiECLGOuIRUWqHPTqQt8AJRPS5BZV38u omega=MEwDAgcAAgEgAiAi5i8vH8TXoSBRetHyzN6OEVu9bAIWvneeHesn1lMcGgIhAKtVmqk4S8cfBIbFSWaGkzELe6CEhiAxJ19IyqmQDxue proof=MEUCIBMoT9on6C1w0NwvXiFrYvZlbHF\/x0OR5D9OqkEDeyepAiEA65PiKA+eHi83vasQhwIqBMWuJvgmQkE9oU3VNv+QJYY= root=ZhrG4hhw9DVXfWlUbndbNeh06QU+vlID+hYg4znYLDU= ot=1
[2018-08-16 15:37:22] [DEBUG]     6 | [xxx.xxx.xxx.xxx:55619/undefined] Got client ek!
[2018-08-16 15:37:22] [DEBUG]     6 | Cant decrypt packet of type Command. Dropping packet. Error: memory verify failed!
[2018-08-16 15:37:22] [DEBUG]   GEN | Invalid packed pushpack! Current index 2 (generation 0) Packet index 1
[2018-08-16 15:37:23] [DEBUG]     6 | Cant decrypt packet of type Command. Dropping packet. Error: memory verify failed!
[2018-08-16 15:37:23] [DEBUG]   GEN | Invalid packed pushpack! Current index 2 (generation 0) Packet index 1
[2018-08-16 15:37:24] [DEBUG]     6 | Cant decrypt packet of type Command. Dropping packet. Error: memory verify failed!
[2018-08-16 15:37:24] [DEBUG]   GEN | Invalid packed pushpack! Current index 2 (generation 0) Packet index 1
[2018-08-16 15:37:25] [DEBUG]     6 | Cant decrypt packet of type Command. Dropping packet. Error: memory verify failed!
[2018-08-16 15:37:25] [DEBUG]   GEN | Invalid packed pushpack! Current index 2 (generation 0) Packet index 1
[2018-08-16 15:37:27] [DEBUG]     6 | [xxx.xxx.xxx.xxx:55619/undefined] Got handshake timeout. xxx.xxx.xxx.xxx:55619. State: INIT_HIGH Time: 5
[2018-08-16 15:37:27] [DEBUG]     6 | [xxx.xxx.xxx.xxx:55619/undefined] Closing voice client connection. (Flush: true)
[2018-08-16 15:37:27] [DEBUG]     6 | [xxx.xxx.xxx.xxx:55619/undefined] Awaiting write prepare, write and acknowledge queue flushed
[2018-08-16 15:37:27] [DEBUG]     6 | [xxx.xxx.xxx.xxx:55619/undefined] Write prepare queue progressed
[2018-08-16 15:37:27] [DEBUG]     6 | [xxx.xxx.xxx.xxx:55619/undefined] Write and acknowledge queue are flushed
[2018-08-16 15:37:27] [INFO]      6 | Voice client 0/mDPaK2/w6gd0w9bCYTiter/FLm8= (undefined) from xxx.xxx.xxx.xxx:55619 left.
[2018-08-16 15:37:27] [DEBUG]     6 | Updating server property: virtualserver_last_client_disconnect. New value: 1534426647. Query: UPDATE `properties` SET `value` = :value WHERE `serverId` = :sid AND `type` = :type AND `id` = :id AND `key` = :key

**Comment by xRedFox** [comment] 2018-08-16 14:05
@Riddler76 and @lemignon please use this for logs:
https://help.github.com/articles/creating-and-highlighting-code-blocks/

```
Example 
Example 
Example 
Example 
```

**Comment by lbenicio** [comment] 2018-08-17 23:04
I'm having the same issue as well, just to let u guys know it still happening. Some clients get over 20 tries and could not connect, some connect after 2-10 tries

**Comment by WolverinDEV** [comment] 2018-09-08 18:14
Should be improved within the last few versions :)
Reopen if still exists

**Closed by WolverinDEV** 2018-09-08 18:14 UTC
Labels: help wanted
